# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa552a25301d302f31f003cb74f3cbb7e8b6e3f1d13445487b7025ac748a96361c0cd460aa82260e47a4904440f9f9620df38a0d67773ae510870b455bde7604

test:
  secret_key_base: 0eab7b53fc19adb0cd99118367ec815ba58ec44144810d0e1150cb842b77f5d4829a73f95c984d26a204a3f7383d0a97bc3903a9a87bceb060a55d02dfeb62a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
